package db;

public class Etfs {
	static final String[] etfs = {
		// ishares
		"CLY", "10+ Year Credit Bond Fund",
		"GLJ", "10+ Year Government/Credit Bond Fund",
		"MUAA", "2012 S&P AMT-Free Municipal Series",
		"MUAB", "2013 S&P AMT-Free Municipal Series",
		"MUAC", "2014 S&P AMT-Free Municipal Series",
		"MUAD", "2015 S&P AMT-Free Municipal Series",
		"MUAE", "2016 S&P AMT-Free Municipal Series",
		"MUAF", "2017 S&P AMT-Free Municipal Series",
		"STIP", "Barclays 0-5 Year TIPS Bond Fund",
		"CSJ", "Barclays 1-3 Year Credit Bond Fund",
		"SHY", "Barclays 1-3 Year Treasury Bond Fund",
		"TLH", "Barclays 10-20 Year Treasury Bond Fund",
		"TLT", "Barclays 20+ Year Treasury Bond Fund",
		"IEI", "Barclays 3-7 Year Treasury Bond Fund",
		"IEF", "Barclays 7-10 Year Treasury Bond Fund",
		"AGZ", "Barclays Agency Bond Fund",
		"AGG", "Barclays Aggregate Bond Fund",
		"CFT", "Barclays Credit Bond Fund",
		"GBF", "Barclays Government/Credit Bond Fund",
		"CIU", "Barclays Intermediate Credit Bond Fund",
		"GVI", "Barclays Intermediate Government/Credit Bond Fund",
		"MBB", "Barclays MBS Bond Fund",
		"SHV", "Barclays Short Treasury Bond Fund",
		"TIP", "Barclays TIPS Bond Fund",
		"ICF", "Cohen & Steers Realty Majors Index Fund",
		"IDV", "Dow Jones International Select Dividend Index Fund",
		"DVY", "Dow Jones Select Dividend Index Fund",
		"IYT", "Dow Jones Transportation Average Index Fund",
		"ITA", "Dow Jones U.S. Aerospace & Defense Index Fund",
		"IYM", "Dow Jones U.S. Basic Materials Sector Index Fund",
		"IAI", "Dow Jones U.S. Broker-Dealers Index Fund",
		"IYK", "Dow Jones U.S. Consumer Goods Sector Index Fund",
		"IYC", "Dow Jones U.S. Consumer Services Sector Index Fund",
		"IYE", "Dow Jones U.S. Energy Sector Index Fund",
		"IYF", "Dow Jones U.S. Financial Sector Index Fund",
		"IYG", "Dow Jones U.S. Financial Services Index Fund",
		"IHF", "Dow Jones U.S. Healthcare Providers Index Fund",
		"IYH", "Dow Jones U.S. Healthcare Sector Index Fund",
		"ITB", "Dow Jones U.S. Home Construction Index Fund",
		"IYY", "Dow Jones U.S. Index Fund",
		"IYJ", "Dow Jones U.S. Industrial Sector Index Fund",
		"IAK", "Dow Jones U.S. Insurance Index Fund",
		"IHI", "Dow Jones U.S. Medical Devices Index Fund",
		"IEO", "Dow Jones U.S. Oil & Gas Exploration & Production Index Fund",
		"IEZ", "Dow Jones U.S. Oil Equipment & Services Index Fund",
		"IHE", "Dow Jones U.S. Pharmaceuticals Index Fund",
		"IYR", "Dow Jones U.S. Real Estate Index Fund",
		"IAT", "Dow Jones U.S. Regional Banks Index Fund",
		"IYW", "Dow Jones U.S. Technology Sector Index Fund",
		"IYZ", "Dow Jones U.S. Telecommunications Sector Index Fund",
		"IDU", "Dow Jones U.S. Utilities Sector Index Fund",
		"FCHI", "FTSE China (HK Listed) Index Fund",
		"FXI", "FTSE China 25 Index Fund",
		"IFSM", "FTSE Developed Small Cap ex-North America Index Fund",
		"IFAS", "FTSE EPRA/NAREIT Developed Asia Index Fund",
		"IFEU", "FTSE EPRA/NAREIT Developed Europe Index Fund",
		"IFGL", "FTSE EPRA/NAREIT Developed Real Estate ex-U.S. Index Fund",
		"IFNA", "FTSE EPRA/NAREIT North America Index Fund",
		"FNIO", "FTSE NAREIT Industrial/Office Capped Index Fund",
		"REM", "FTSE NAREIT Mortgage Plus Capped Index Fund",
		"FTY", "FTSE NAREIT Real Estate 50 Index Fund",
		"REZ", "FTSE NAREIT Residential Plus Capped Index Fund",
		"RTL", "FTSE NAREIT Retail Capped Index Fund",
		"FLOT", "Floating Rate Note Fund",
		"GTIP", "Global Inflation-Linked Bond Fund",
		"HDV", "High Dividend Equity Fund",
		"ITIP", "International Inflation-Linked Bond Fund",
		"EMB", "JPMorgan USD Emerging Markets Bond Fund",
		"ACWI", "MSCI ACWI Index Fund",
		"AXDI", "MSCI ACWI ex US Consumer Discretionary Sector Index Fund",
		"AXSL", "MSCI ACWI ex US Consumer Staples Sector Index Fund",
		"AXEN", "MSCI ACWI ex US Energy Sector Index Fund",
		"AXFN", "MSCI ACWI ex US Financials Sector Index Fund",
		"AXHE", "MSCI ACWI ex US Health Care Sector Index Fund",
		"ACWX", "MSCI ACWI ex US Index Fund",
		"AXID", "MSCI ACWI ex US Industrials Sector Index Fund",
		"AXIT", "MSCI ACWI ex US Information Technology Sector Index Fund",
		"AXMT", "MSCI ACWI ex US Materials Sector Index Fund",
		"AXTE", "MSCI ACWI ex US Telecommunication Services Sector Index Fund",
		"AXUT", "MSCI ACWI ex US Utilities Sector Index Fund",
		"AAXJ", "MSCI All Country Asia ex Japan Index Fund",
		"EPU", "MSCI All Peru Capped Index Fund",
		"EWA", "MSCI Australia Index Fund",
		"EWO", "MSCI Austria Investable Market Index Fund",
		"BKF", "MSCI BRIC Index Fund",
		"EWK", "MSCI Belgium Investable Market Index Fund",
		"EWZ", "MSCI Brazil Index Fund",
		"EWZS", "MSCI Brazil Small Cap Index Fund",
		"EWC", "MSCI Canada Index Fund",
		"ECH", "MSCI Chile Investable Market Index Fund",
		"MCHI", "MSCI China Index Fund",
		"ECNS", "MSCI China Small Cap Index Fund",
		"EFG", "MSCI EAFE Growth Index Fund",
		"EFA", "MSCI EAFE Index Fund",
		"SCZ", "MSCI EAFE Small Cap Index Fund",
		"EFV", "MSCI EAFE Value Index Fund",
		"EZU", "MSCI EMU Index Fund",
		"ESR", "MSCI Emerging Markets Eastern Europe Index Fund",
		"EMFN", "MSCI Emerging Markets Financials Sector Index Fund",
		"EEM", "MSCI Emerging Markets Index Fund",
		"EMMT", "MSCI Emerging Markets Materials Sector Index Fund",
		"EEMS", "MSCI Emerging Markets Small Cap Index Fund",
		"EUFN", "MSCI Europe Financials Sector Index Fund",
		"FEFN", "MSCI Far East Financials Sector Index Fund",
		"EWQ", "MSCI France Index Fund",
		"EWG", "MSCI Germany Index Fund",
		"EWH", "MSCI Hong Kong Index Fund",
		"EIDO", "MSCI Indonesia Investable Market Index Fund",
		"EIRL", "MSCI Ireland Capped Investable Market Index Fund",
		"EIS", "MSCI Israel Capped Investable Market Index Fund",
		"EWI", "MSCI Italy Index Fund",
		"EWJ", "MSCI Japan Index Fund",
		"SCJ", "MSCI Japan Small Cap Index Fund",
		"DSI", "MSCI KLD 400 Social Index Fund",
		"TOK", "MSCI Kokusai Index Fund",
		"EWM", "MSCI Malaysia Index Fund",
		"EWW", "MSCI Mexico Investable Market Index Fund",
		"EWN", "MSCI Netherlands Investable Market Index Fund",
		"ENZL", "MSCI New Zealand Investable Market Index Fund",
		"EPP", "MSCI Pacific ex-Japan Index Fund",
		"EPHE", "MSCI Philippines Investable Market Index Fund",
		"EPOL", "MSCI Poland Investable Market Index Fund",
		"ERUS", "MSCI Russia Capped Index Fund",
		"EWS", "MSCI Singapore Index Fund",
		"EZA", "MSCI South Africa Index Fund",
		"EWY", "MSCI South Korea Index Fund",
		"EWP", "MSCI Spain Index Fund",
		"EWD", "MSCI Sweden Index Fund",
		"EWL", "MSCI Switzerland Index Fund",
		"EWT", "MSCI Taiwan Index Fund",
		"THD", "MSCI Thailand Investable Market Index Fund",
		"TUR", "MSCI Turkey Investable Market Index Fund",
		"KLD", "MSCI USA ESG Select Social Index Fund",
		"EUSA", "MSCI USA Index Fund",
		"EWU", "MSCI United Kingdom Index Fund",
		"JKD", "Morningstar Large Core Index Fund",
		"JKE", "Morningstar Large Growth Index Fund",
		"JKF", "Morningstar Large Value Index Fund",
		"JKG", "Morningstar Mid Core Index Fund",
		"JKH", "Morningstar Mid Growth Index Fund",
		"JKI", "Morningstar Mid Value Index Fund",
		"JKJ", "Morningstar Small Core Index Fund",
		"JKK", "Morningstar Small Growth Index Fund",
		"JKL", "Morningstar Small Value Index Fund",
		"NY", "NYSE 100 Index Fund",
		"NYC", "NYSE Composite Index Fund",
		"IBB", "Nasdaq Biotechnology Index Fund",
		"SOXX", "PHLX SOX Semiconductor Sector Index Fund",
		"IWF", "Russell 1000 Growth Index Fund",
		"IWB", "Russell 1000 Index Fund",
		"IWD", "Russell 1000 Value Index Fund",
		"IWO", "Russell 2000 Growth Index Fund",
		"IWM", "Russell 2000 Index Fund",
		"IWN", "Russell 2000 Value Index Fund",
		"IWZ", "Russell 3000 Growth Index Fund",
		"IWV", "Russell 3000 Index Fund",
		"IWW", "Russell 3000 Value Index Fund",
		"IWC", "Russell Microcap(R) Index Fund",
		"IWP", "Russell Midcap Growth Index Fund",
		"IWR", "Russell Midcap Index Fund",
		"IWS", "Russell Midcap Value Index Fund",
		"IWY", "Russell Top 200 Growth Index Fund",
		"IWL", "Russell Top 200 Index Fund",
		"IWX", "Russell Top 200 Value Index Fund",
		"OEF", "S&P 100 Index Fund",
		"ISI", "S&P 1500 Index Fund",
		"IVW", "S&P 500 Growth Index Fund",
		"IVV", "S&P 500 Index Fund",
		"IVE", "S&P 500 Value Index Fund",
		"AOA", "S&P Aggressive Allocation Fund",
		"AIA", "S&P Asia 50 Index Fund",
		"CMF", "S&P California AMT-Free Municipal Bond Fund",
		"AOK", "S&P Conservative Allocation Fund",
		"WPS", "S&P Developed ex-U.S. Property Index Fund",
		"EMIF", "S&P Emerging Markets Infrastructure Index Fund",
		"IEV", "S&P Europe 350 Index Fund",
		"IOO", "S&P Global 100 Index Fund",
		"ICLN", "S&P Global Clean Energy Index Fund",
		"RXI", "S&P Global Consumer Discretionary Sector Index Fund",
		"KXI", "S&P Global Consumer Staples Sector Index Fund",
		"IXC", "S&P Global Energy Sector Index Fund",
		"IXG", "S&P Global Financials Sector Index Fund",
		"IXJ", "S&P Global Healthcare Sector Index Fund",
		"EXI", "S&P Global Industrials Sector Index Fund",
		"IGF", "S&P Global Infrastructure Index Fund",
		"MXI", "S&P Global Materials Sector Index Fund",
		"NUCL", "S&P Global Nuclear Energy Index Fund",
		"IXN", "S&P Global Technology Sector Index Fund",
		"IXP", "S&P Global Telecommunications Sector Index Fund",
		"WOOD", "S&P Global Timber & Forestry",
		"JXI", "S&P Global Utilities Sector Index Fund",
		"AOR", "S&P Growth Allocation Fund",
		"INDY", "S&P India Nifty 50 Index Fund",
		"ILF", "S&P Latin America 40 Index Fund",
		"IJK", "S&P MidCap 400 Growth Index Fund",
		"IJH", "S&P MidCap 400 Index Fund",
		"IJJ", "S&P MidCap 400 Value Index Fund",
		"AOM", "S&P Moderate Allocation Fund",
		"MUB", "S&P National AMT-Free Municipal Bond Fund",
		"NYF", "S&P New York AMT-Free Municipal Bond Fund",
		"IGE", "S&P North American Natural Resources Sector Index Fund",
		"IGM", "S&P North American Technology Sector Index Fund",
		"IGN", "S&P North American Technology-Multimedia Networking Index Fund",
		"IGV", "S&P North American Technology-Software Index Fund",
		"SUB", "S&P Short Term National AMT-Free Municipal Bond Fund",
		"IJT", "S&P SmallCap 600 Growth Index Fund",
		"IJR", "S&P SmallCap 600 Index Fund",
		"IJS", "S&P SmallCap 600 Value Index Fund",
		"TZD", "S&P Target Date 2010 Index Fund",
		"TZE", "S&P Target Date 2015 Index Fund",
		"TZG", "S&P Target Date 2020 Index Fund",
		"TZI", "S&P Target Date 2025 Index Fund",
		"TZL", "S&P Target Date 2030 Index Fund",
		"TZO", "S&P Target Date 2035 Index Fund",
		"TZV", "S&P Target Date 2040 Index Fund",
		"TZW", "S&P Target Date 2045 Index Fund",
		"TZY", "S&P Target Date 2050 Index Fund",
		"TGR", "S&P Target Date Retirement Income Index Fund",
		"PFF", "S&P U.S. Preferred Stock Index Fund",
		"ISHG", "S&P/Citigroup 1-3 Year International Treasury Bond Fund",
		"IGOV", "S&P/Citigroup International Treasury Bond Fund",
		"ITF", "S&P/TOPIX 150 Index Fund",
		"HYG", "iBoxx $ High Yield Corporate Bond Fund",
		"LQD", "iBoxx $ Investment Grade Corporate Bond Fund",
		
		// spyder
		"BABS", "SPDR Nuveen Barclays Capital Build America Bond ETF",
		"BIK", "SPDR S&P BRIC 40 ETF",
		"BIL", "SPDR Barclays Capital 1-3 Month T-Bill ETF",
		"BWX", "SPDR Barclays Capital International Treasury Bond ETF",
		"BWZ", "SPDR Barclays Capital Short Term International Treasury Bond ETF",
		"CBND", "SPDR Barclays Capital Issuer Scored Corporate Bond ETF",
		"CWB", "SPDR Barclays Capital Convertible Securities ETF",
		"CWI", "SPDR MSCI ACWI ex-US ETF",
		"CXA", "SPDR Nuveen Barclays Capital California Municipal Bond ETF",
		"DGT", "SPDR Global Dow ETF",
		"DIA", "SPDR Dow Jones Industrial Average ETF",
		"DWX", "SPDR S&P International Dividend ETF",
		"EBND", "SPDR Barclays Capital Emerging Markets Local Bond ETF",
		"EDIV", "SPDR S&P Emerging Markets Dividend ETF",
		"ELR", "SPDR Dow Jones Large Cap ETF",
		"EMM", "SPDR Dow Jones Mid Cap ETF",
		"EWX", "SPDR S&P Emerging Markets Small Cap ETF",
		"FEU", "SPDR STOXX Europe 50 ETF ",
		"FEZ", "SPDR EURO STOXX 50 ETF",
		"GAF", "SPDR S&P Emerging Middle East & Africa ETF",
		"GII", "SPDR FTSE/Macquarie Global Infrastructure 100 ETF",
		"GLD", "SPDR Gold Shares",
		"GMF", "SPDR S&P Emerging Asia Pacific ETF",
		"GML", "SPDR S&P Emerging Latin America ETF",
		"GMM", "SPDR S&P Emerging Markets ETF",
		"GNR", "SPDR S&P Global Natural Resources ETF",
		"GUR", "SPDR S&P Emerging Europe ETF",
		"GWL", "SPDR S&P World ex-US ETF",
		"GWX", "SPDR S&P International Small Cap ETF",
		"GXC", "SPDR S&P China ETF",
		"HYMB", "SPDR Nuveen S&P High Yield Municipal Bond ETF",
		"IBND", "SPDR Barclays Capital International Corporate Bond ETF",
		"INY", "SPDR Nuveen Barclays Capital New York Municipal Bond ETF",
		"IPD", "SPDR S&P International Consumer Discretionary Sector ETF",
		"IPE", "SPDR Barclays Capital TIPS ETF",
		"IPF", "SPDR S&P International Financial Sector ETF",
		"IPK", "SPDR S&P International Technology Sector ETF",
		"IPN", "SPDR S&P International Industrial Sector ETF",
		"IPS", "SPDR S&P International Consumer Staples Sector ETF",
		"IPU", "SPDR S&P International Utilities Sector ETF",
		"IPW", "SPDR S&P International Energy Sector ETF",
		"IRV", "SPDR S&P International Materials Sector ETF",
		"IRY", "SPDR S&P International Health Care Sector ETF",
		"IST", "SPDR S&P International Telecommunications Sector ETF",
		"ITE", "SPDR Barclays Capital Intermediate Term Treasury ETF",
		"ITR", "SPDR Barclays Capital Intermediate Term Corporate Bond ETF",
		"JNK", "SPDR Barclays Capital High Yield Bond ETF",
		"JPP", "SPDR Russell/Nomura PRIME Japan ETF",
		"JSC", "SPDR Russell/Nomura Small Cap Japan ETF",
		"KBE", "SPDR S&P Bank ETF",
		"KCE", "SPDR S&P Capital Markets ETF",
		"KIE", "SPDR S&P Insurance ETF",
		"KME", "SPDR S&P Mortgage Finance ETF",
		"KRE", "SPDR S&P Regional Banking ETF",
		"LAG", "SPDR Barclays Capital Aggregate Bond ETF",
		"LWC", "SPDR Barclays Capital Long Term Corporate Bond ETF",
		"MBG", "SPDR Barclays Capital Mortgage Backed Bond ETF",
		"MDD", "SPDR S&P International Mid Cap ETF",
		"MDY", "SPDR S&P MidCap 400 ETF",
		"MDYG", "SPDR S&P 400 Mid Cap Growth ETF",
		"MDYV", "SPDR S&P 400 Mid Cap Value ETF",
		"MTK", "SPDR Morgan Stanley Technology ETF",
		"PSK", "SPDR Wells Fargo Preferred Stock ETF",
		"RBL", "SPDR S&P Russia ETF",
		"RWO", "SPDR Dow Jones Global Real Estate ETF",
		"RWR", "SPDR Dow Jones REIT ETF",
		"RWX", "SPDR Dow Jones International Real Estate ETF",
		"SCPB", "SPDR Barclays Capital Short Term Corporate Bond ETF",
		"SDY", "SPDR S&P Dividend ETF",
		"SHM", "SPDR Nuveen Barclays Capital Short Term Municipal Bond ETF",
		"SLY", "SPDR S&P 600 Small Cap ETF",
		"SLYG", "SPDR S&P 600 Small Cap Growth ETF",
		"SLYV", "SPDR S&P 600 Small Cap Value ETF",
		"SPY", "SPDR S&P 500",
		"SPYG", "SPDR S&P 500 Growth ETF",
		"SPYV", "SPDR S&P 500 Value ETF",
		"TFI", "SPDR Nuveen Barclays Capital Municipal Bond ETF",
		"TLO", "SPDR Barclays Capital Long Term Treasury ETF",
		"TMW", "SPDR Dow Jones Total Market ETF",
		"VRD", "SPDR Nuveen S&P VRDO Municipal Bond ETF",
		"WIP", "SPDR DB International Government Inflation-Protected Bond ETF",
		"XAR", "SPDR S&P Aerospace & Defense ETF ",
		"XBI", "SPDR S&P Biotech ETF",
		"XES", "SPDR S&P Oil & Gas Equipment & Services ETF",
		"XHB", "SPDR S&P Homebuilders ETF",
		"XHE", "SPDR S&P Health Care Equipment ETF",
		"XHS", "SPDR S&P Health Care Services ETF",
		"XLB", "Materials Select Sector SPDR Fund",
		"XLE", "Energy Select Sector SPDR Fund",
		"XLF", "Financial Select Sector SPDR Fund",
		"XLI", "Industrial Select Sector SPDR Fund",
		"XLK", "Technology Select Sector SPDR Fund",
		"XLP", "Consumer Staples Select Sector SPDR Fund",
		"XLU", "Utilities Select Sector SPDR Fund",
		"XLV", "Health Care Select Sector SPDR Fund",
		"XLY", "Consumer Discretionary Select Sector SPDR Fund",
		"XME", "SPDR S&P Metals and Mining ETF",
		"XOP", "SPDR S&P Oil & Gas Exploration & Production ETF",
		"XPH", "SPDR S&P Pharmaceuticals ETF",
		"XRT", "SPDR S&P Retail ETF",
		"XSD", "SPDR S&P Semiconductor ETF",
		"XSW", "SPDR S&P Software & Services ETF ",
		"XTL", "SPDR S&P Telecom ETF",
		"XTN", "SPDR S&P Transportation ETF",
		
		// powershares
		"PLK", "Active Low Duration Fund",
		"PMA", "Active Mega Cap Fund",
		"PSR", "Active U.S. Real Estate Fund",
		"PTO", "Ibbotson Alternative Completion",
		"PAO", "RiverFront Tactical Balanced Growth Portfolio",
		"PCA", "RiverFront Tactical Growth & Income Portfolio",
		"PWC", "Dynamic Market Portfolio",
		"PWO", "Dynamic OTC Portfolio",
		"PIQ", "Dynamic MagniQuant Portfolio",
		"PRF", "FTSE RAFI US 1000 Portfolio",
		"PRFZ", "FTSE RAFI US 1500 Small-Mid Portfolio",
		"DBE", "DB Energy Fund",
		"DBA", "DB Agriculture Fund",
		"DBB", "DB Base Metals Fund",
		"DBO", "DB Oil Fund",
		"DBS", "DB Silver Fund",
		"DBP", "DB Precious Metals Fund",
		"DGL", "DB Gold Fund",
		"DBC", "DB Commodity Index Tracking Fund",
		"DBV", "DB G10 Currency Harvest Fund",
		"UDN", "DB US Dollar Bearish Fund",
		"UUP", "DB US Dollar Bullish Fund",
		"PAGG", "Global Agriculture Portfolio ",
		"PKOL", "Global Coal Portfolio ",
		"PSAU", "Global Gold and Precious Metals Portfolio ",
		"PSTL", "Global Steel Portfolio",
		"PKW", "Buyback Achievers Portfolio",
		"PCEF", "CEF Income Composite Portfolio",
		"PFM", "Dividend Achievers Portfolio",
		"PEY", "High Yield Equity Dividend Achievers Portfolio",
		"KBWD", "KBW High Dividend Yield Financial Portfolio",
		"KBWY", "KBW Premium Yield Equity REIT Portfolio ",
		"PLW", "1-30 Laddered Treasury Portfolio",
		"BAB", "Build America Bond Portfolio",
		"PCY", "Emerging Markets Sovereign Debt Portfolio",
		"DSUM", "Chinese Yuan Dim Sum Bond Portfolio",
		"PFIG", "Fundamental Investment Grade Corporate Bond Portfolio",
		"PHB", "Fundamental High Yield Corporate Bond Portfolio",
		"PZA", "Insured National Municipal Bond Portfolio",
		"PWZ", "Insured California Municipal Bond Portfolio",
		"PZT", "Insured New York Municipal Bond Portfolio",
		"PICB", "International Corporate Bond Portfolio ",
		"BKLN", "Senior Loan Portfolio",
		"PVI", "VRDO Tax-Free Weekly Portfolio",
		"CVRT", "Convertible Securities Portfolio",
		"PGF", "Financial Preferred Portfolio",
		"PGX", "Preferred Portfolio",
		"PZD", "Cleantech Portfolio",
		"PIZ", "DWA Developed Markets Technical Leaders Portfolio",
		"PIE", "DWA Emerging Markets Technical Leaders Portfolio",
		"PFA", "Dynamic Developed International Opportunities Portfolio",
		"PXR", "Emerging Markets Infrastructure Portfolio",
		"PAF", "FTSE RAFI Asia Pacific ex-Japan Portfolio",
		"PXF", "FTSE RAFI Developed Markets ex-U.S. Portfolio",
		"PDN", "FTSE RAFI Developed Markets ex-U.S. Small-Mid Portfolio",
		"PXH", "FTSE RAFI Emerging Markets Portfolio",
		"PBD", "Global Clean Energy Portfolio",
		"PSP", "Global Listed Private Equity Portfolio",
		"PKN", "Global Nuclear Energy Portfolio",
		"PIO", "Global Water Portfolio",
		"PWND", "Global Wind Energy Portfolio",
		"PGJ", "Golden Dragon Halter USX China Portfolio",
		"PIN", "India Portfolio",
		"PID", "International Dividend Achievers Portfolio",
		"KBWX", "KBW International Financial Portfolio ",
		"PMNA", "MENA Frontier Countries Portfolio",
		"PWB", "Dynamic Large Cap Growth Portfolio",
		"PWV", "Dynamic Large Cap Value Portfolio",
		"PXLC", "Fundamental Pure Large Core Portfolio",
		"PXLG", "Fundamental Pure Large Growth Portfolio",
		"PXLV", "Fundamental Pure Large Value Portfolio",
		"PXMC", "Fundamental Pure Mid Core Portfolio",
		"PXMG", "Fundamental Pure Mid Growth Portfolio",
		"PXMV", "Fundamental Pure Mid Value Portfolio",
		"PXSC", "Fundamental Pure Small Core Portfolio",
		"PXSG", "Fundamental Pure Small Growth Portfolio",
		"PXSV", "Fundamental Pure Small Value Portfolio",
		"PZI", "Zacks Micro Cap Portfolio",
		"QQQ", "PowerShares QQQ",
		"ADRA", "BLDRS Asia 50 ADR Index Fund",
		"ADRD", "BLDRS Developed Markets 100 ADR Index Fund",
		"ADRE", "BLDRS Emerging Markets 50 ADR Index Fund",
		"ADRU", "BLDRS Europe Select ADR Index Fund",
		"PDP", "DWA Technical Leaders Portfolio",
		"PYH", "Morningstar StockInvestor Core Portfolio",
		"PBP", "S&P 500 BuyWrite Portfolio",
		"SPHB", "S&P 500 High Beta Portfolio",
		"PIV", "S&P 500 High Quality Portfolio",
		"SPLV", "S&P 500 Low Volatility Portfolio",
		"PPA", "Aerospace & Defense Portfolio",
		"PXN", "Lux Nanotech Portfolio",
		"PNQI", "NASDAQ Internet Portfolio",
		"PHO", "Water Resources Portfolio",
		"PBW", "WilderHill Clean Energy Portfolio",
		"PUW", "WilderHill Progressive Energy Portfolio",
		"PJB", "Dynamic Banking Portfolio",
		"PYZ", "Dynamic Basic Materials Sector Portfolio",
		"PBE", "Dynamic Biotechnology & Genome Portfolio",
		"PKB", "Dynamic Building & Construction Portfolio",
		"PEZ", "Dynamic Consumer Discretionary Sector Portfolio",
		"PXI", "Dynamic Energy Sector Portfolio",
		"PSL", "Dynamic Consumer Staples Sector Portfolio",
		"PXE", "Dynamic Energy Exploration & Production Portfolio",
		"PFI", "Dynamic Financial Sector Portfolio",
		"PBJ", "Dynamic Food & Beverage Portfolio",
		"PTH", "Dynamic Healthcare Sector Portfolio",
		"PRN", "Dynamic Industrials Sector Portfolio",
		"PIC", "Dynamic Insurance Portfolio",
		"PEJ", "Dynamic Leisure and Entertainment Portfolio",
		"PBS", "Dynamic Media Portfolio",
		"PXQ", "Dynamic Networking Portfolio",
		"PXJ", "Dynamic Oil & Gas Services Portfolio",
		"PJP", "Dynamic Pharmaceuticals Portfolio",
		"PMR", "Dynamic Retail Portfolio",
		"PSI", "Dynamic Semiconductors Portfolio",
		"PSJ", "Dynamic Software Portfolio",
		"PTF", "Dynamic Technology Sector Portfolio",
		"PUI", "Dynamic Utilities Portfolio",
		"KBWI", "KBW Insurance Portfolio",
		"KBWP", "KBW Property & Casualty Insurance Portfolio",
		"KBWR", "KBW Regional Bank Portfolio",
		"KBWB", "KBW Bank Portfolio",
		"KBWC", "KBW Capital Markets Portfolio",
		"PSCD", "S&P SmallCap Consumer Discretionary Portfolio",
		"PSCC", "S&P SmallCap Consumer Staples Portfolio",
		"PSCE", "S&P SmallCap Energy Portfolio",
		"PSCF", "S&P SmallCap Financials Portfolio",
		"PSCH", "S&P SmallCap Health Care Portfolio",
		"PSCI", "S&P SmallCap Industrials Portfolio",
		"PSCT", "S&P SmallCap Information Technology Portfolio",
		"PSCM", "S&P SmallCap Materials Portfolio",
		"PSCU", "S&P SmallCap Utilities Portfolio",		
	};
}
